+incdir+../rtl_vx
+incdir+../rtl_vx/interfaces
+incdir+../rtl_vx/libs
+incdir+../rtl_vx/fpu
+incdir+../rtl_vx/core
+incdir+../rtl_vx/mem
+incdir+../rtl_vx/cache

../rtl_vx/VX_config.vh
../rtl_vx/VX_define.vh
../rtl_vx/VX_types.vh
../rtl_vx/VX_platform.vh
../rtl_vx/VX_scope.vh

../rtl_vx/VX_gpu_pkg.sv
../rtl_vx/core/VX_trace_pkg.sv

../rtl_vx/libs/VX_sp_ram.sv
../rtl_vx/libs/VX_index_buffer.sv
../rtl_vx/libs/VX_scope_tap.sv
../rtl_vx/libs/VX_elastic_buffer.sv
../rtl_vx/libs/VX_mem_scheduler.sv
../rtl_vx/libs/VX_bits_insert.sv
../rtl_vx/libs/VX_stream_arb.sv
../rtl_vx/libs/VX_reduce.sv
../rtl_vx/libs/VX_reset_relay.sv
../rtl_vx/libs/VX_bits_remove.sv
../rtl_vx/libs/VX_onehot_encoder.sv
../rtl_vx/libs/VX_mem_adapter.sv
../rtl_vx/libs/VX_scan.sv
../rtl_vx/libs/VX_index_queue.sv
../rtl_vx/libs/VX_avs_adapter.sv
../rtl_vx/libs/VX_onehot_mux.sv
../rtl_vx/libs/VX_pe_serializer.sv
../rtl_vx/libs/VX_toggle_buffer.sv
../rtl_vx/libs/VX_stream_xbar.sv
../rtl_vx/libs/VX_rr_arbiter.sv
../rtl_vx/libs/VX_dp_ram.sv
../rtl_vx/libs/VX_serial_div.sv
../rtl_vx/libs/VX_fifo_queue.sv
../rtl_vx/libs/VX_matrix_arbiter.sv
../rtl_vx/libs/VX_divider.sv
../rtl_vx/libs/VX_popcount.sv
../rtl_vx/libs/VX_pending_size.sv
../rtl_vx/libs/VX_allocator.sv
../rtl_vx/libs/VX_serial_mul.sv
../rtl_vx/libs/VX_stream_pack.sv
../rtl_vx/libs/VX_stream_unpack.sv
../rtl_vx/libs/VX_generic_arbiter.sv
../rtl_vx/libs/VX_cyclic_arbiter.sv
../rtl_vx/libs/VX_stream_buffer.sv
../rtl_vx/libs/VX_shift_register.sv
../rtl_vx/libs/VX_stream_switch.sv
../rtl_vx/libs/VX_mux.sv
../rtl_vx/libs/VX_axi_adapter.sv
../rtl_vx/libs/VX_priority_encoder.sv
../rtl_vx/libs/VX_mem_coalescer.sv
../rtl_vx/libs/VX_lzc.sv
../rtl_vx/libs/VX_pipe_register.sv
../rtl_vx/libs/VX_priority_arbiter.sv
../rtl_vx/libs/VX_elastic_adapter.sv
../rtl_vx/libs/VX_pipe_buffer.sv
../rtl_vx/libs/VX_find_first.sv
../rtl_vx/libs/VX_scope_switch.sv
../rtl_vx/libs/VX_multiplier.sv
../rtl_vx/libs/VX_fair_arbiter.sv
../rtl_vx/libs/VX_skid_buffer.sv
../rtl_vx/libs/VX_bypass_buffer.sv

../rtl_vx/mem/VX_gbar_arb.sv
../rtl_vx/mem/VX_mem_bus_if.sv
../rtl_vx/mem/VX_mem_arb.sv
../rtl_vx/mem/VX_mem_switch.sv
../rtl_vx/mem/VX_gbar_unit.sv
../rtl_vx/mem/VX_mem_perf_if.sv
../rtl_vx/mem/VX_gbar_bus_if.sv

../rtl_vx/interfaces/VX_decode_if.sv
../rtl_vx/interfaces/VX_operands_if.sv
../rtl_vx/interfaces/VX_pipeline_perf_if.sv
../rtl_vx/interfaces/VX_scoreboard_if.sv
../rtl_vx/interfaces/VX_dcr_bus_if.sv
../rtl_vx/interfaces/VX_sfu_perf_if.sv
../rtl_vx/interfaces/VX_lsu_mem_if.sv
../rtl_vx/interfaces/VX_warp_ctl_if.sv
../rtl_vx/interfaces/VX_writeback_if.sv
../rtl_vx/interfaces/VX_branch_ctl_if.sv
../rtl_vx/interfaces/VX_schedule_if.sv
../rtl_vx/interfaces/VX_commit_if.sv
../rtl_vx/interfaces/VX_ibuffer_if.sv
../rtl_vx/interfaces/VX_fetch_if.sv
../rtl_vx/interfaces/VX_sched_csr_if.sv
../rtl_vx/interfaces/VX_commit_csr_if.sv
../rtl_vx/interfaces/VX_dispatch_if.sv
../rtl_vx/interfaces/VX_decode_sched_if.sv
../rtl_vx/interfaces/VX_commit_sched_if.sv
../rtl_vx/interfaces/VX_execute_if.sv

../rtl_vx/core/VX_alu_unit.sv
../rtl_vx/core/VX_operands.sv
../rtl_vx/core/VX_issue_slice.sv
../rtl_vx/core/VX_issue_top.sv
../rtl_vx/core/VX_csr_unit.sv
../rtl_vx/core/VX_split_join.sv
../rtl_vx/core/VX_sfu_unit.sv
../rtl_vx/core/VX_lsu_adapter.sv
../rtl_vx/core/VX_dcr_data.sv
../rtl_vx/core/VX_execute.sv
../rtl_vx/core/VX_core.sv
../rtl_vx/core/VX_schedule.sv
../rtl_vx/core/VX_lsu_unit.sv
../rtl_vx/core/VX_fetch.sv
../rtl_vx/core/VX_alu_int.sv
../rtl_vx/core/VX_decode.sv
../rtl_vx/core/VX_dispatch.sv
../rtl_vx/core/VX_dispatch_unit.sv
../rtl_vx/core/VX_csr_data.sv
../rtl_vx/core/VX_scoreboard.sv
../rtl_vx/core/VX_alu_muldiv.sv
../rtl_vx/core/VX_commit.sv
../rtl_vx/core/VX_issue.sv
../rtl_vx/core/VX_wctl_unit.sv
../rtl_vx/core/VX_gather_unit.sv
../rtl_vx/core/VX_ibuffer.sv
../rtl_vx/core/VX_lsu_slice.sv
../rtl_vx/core/VX_ipdom_stack.sv
../rtl_vx/core/VX_core_top.sv
